# Site settings
title: Siyuan Liu
description: 'Business Card Page'
url: 'https://siyuan-albert.github.io/'
baseurl: ''
profilepic: '/images/tzuehlke.jpg'
bkimage: '/images/bk1.jpg'
google_analytics: UA-XXXXXX-X
font_awesome: 'XXXXXXXXXX.js'

author:
  name: 'Siyuan Liu'
  email: siyuanliu0110@gmail.com
  twitter_username: Siyuan Liu

  github_username:  Siyuan-Albert
  linkedin_username:  siyuan-liu-3a0b24178
  #meetup_name: Azure-Meetup-Rostock-MV

# Build settings
destination: _site
markdown: kramdown
highlighter: rouge

sass:
    sass_dir: _sass
    style: compressed

kramdown:
  # use Github Flavored Markdown
  input: GFM
  # do not replace newlines by <br>s
  hard_wrap: false

#plugins: ['jekyll-paginate']
exclude: ['README.md', 'screenshot-overview.png']
